import { ImageSourcePropType } from 'react-native';
import google from '@/assets/icons/google.png';
import home from '@/assets/icons/home.png';
import search from '@/assets/icons/search.png';
import person from '@/assets/icons/person.png';
import bell from '@/assets/icons/bell.png';
import filter from '@/assets/icons/filter.png';
import star from '@/assets/icons/star.png';
import heart from '@/assets/icons/heart.png';
import backArrow from '@/assets/icons/back-arrow.png';
import calendar from '@/assets/icons/calendar.png';
import info from '@/assets/icons/info.png';
import language from '@/assets/icons/language.png';
import logout from '@/assets/icons/logout.png';
import people from '@/assets/icons/people.png';
import shield from '@/assets/icons/shield.png';
import wallet from '@/assets/icons/wallet.png';
import rightArrow from '@/assets/icons/right-arrow.png';
import send from '@/assets/icons/send.png';
import bed from '@/assets/icons/bed.png';
import bath from '@/assets/icons/bath.png';
import area from '@/assets/icons/area.png';
import chat from '@/assets/icons/chat.png';
import phone from '@/assets/icons/phone.png';
import carPark from '@/assets/icons/car-park.png';
import cutlery from '@/assets/icons/cutlery.png';
import dog from '@/assets/icons/dog.png';
import dumbell from '@/assets/icons/dumbell.png';
import laundry from '@/assets/icons/laundry.png';
import run from '@/assets/icons/run.png';
import swim from '@/assets/icons/swim.png';
import wifi from '@/assets/icons/wifi.png';
import location from '@/assets/icons/location.png';
import edit from '@/assets/icons/edit.png';

const icons = {
  google: google as ImageSourcePropType,
  home: home as ImageSourcePropType,
  search: search as ImageSourcePropType,
  person: person as ImageSourcePropType,
  bell: bell as ImageSourcePropType,
  filter: filter as ImageSourcePropType,
  star: star as ImageSourcePropType,
  heart: heart as ImageSourcePropType,
  backArrow: backArrow as ImageSourcePropType,
  calendar: calendar as ImageSourcePropType,
  info: info as ImageSourcePropType,
  language: language as ImageSourcePropType,
  logout: logout as ImageSourcePropType,
  people: people as ImageSourcePropType,
  shield: shield as ImageSourcePropType,
  wallet: wallet as ImageSourcePropType,
  rightArrow: rightArrow as ImageSourcePropType,
  send: send as ImageSourcePropType,
  bed: bed as ImageSourcePropType,
  bath: bath as ImageSourcePropType,
  area: area as ImageSourcePropType,
  chat: chat as ImageSourcePropType,
  phone: phone as ImageSourcePropType,
  carPark: carPark as ImageSourcePropType,
  cutlery: cutlery as ImageSourcePropType,
  dog: dog as ImageSourcePropType,
  dumbell: dumbell as ImageSourcePropType,
  laundry: laundry as ImageSourcePropType,
  run: run as ImageSourcePropType,
  swim: swim as ImageSourcePropType,
  wifi: wifi as ImageSourcePropType,
  location: location as ImageSourcePropType,
  edit: edit as ImageSourcePropType,
};

export default icons;
